In [1]:
import numpy as np

In [5]:
A = np.array([[1, 2, 3, 4, 5], 
              [6, 7, 8, 9, 10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
B=np.array([[0, 1, 1, 2, 3],[ 5, 8, 13, 21, 34],[ 55, 89, 144, 233, 377],[ 610, 987, 1597, 2584, 4181],[ 6765, 10946, 17711, 28657, 46368]])
B

array([[    0,     1,     1,     2,     3],
       [    5,     8,    13,    21,    34],
       [   55,    89,   144,   233,   377],
       [  610,   987,  1597,  2584,  4181],
       [ 6765, 10946, 17711, 28657, 46368]])

In [8]:
C=A+B
C

array([[    1,     3,     4,     6,     8],
       [   11,    15,    21,    30,    44],
       [   66,   101,   157,   247,   392],
       [  626,  1004,  1615,  2603,  4201],
       [ 6786, 10968, 17734, 28681, 46393]])

In [9]:
D=([[23, 21, 20, 13, 15],[ 18, 24, 21, 8, 5],[ 20, 3, 25, 6, 3], [1, 4, 11, 19, 12], [25, 15, 12, 12,24]])
D

[[23, 21, 20, 13, 15],
 [18, 24, 21, 8, 5],
 [20, 3, 25, 6, 3],
 [1, 4, 11, 19, 12],
 [25, 15, 12, 12, 24]]