In [ ]:
import numpy as np#импортируем библиотеку

In [20]:
A = np.array([[1, 2, 3, 4, 5], #пишем любую матрицу 5 на 5
              [6, 7, 8, 9, 10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]])
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
B=np.array([[0, 1, 1, 2, 3],[ 5, 8, 13, 21, 34],[ 55, 89, 144, 233, 377],[ 610, 987, 1597, 2584, 4181],[ 6765, 10946, 17711, 28657, 46368]])#заполняем
#матрицу 5 на 5 рядом фибоначчи
B

array([[    0,     1,     1,     2,     3],
       [    5,     8,    13,    21,    34],
       [   55,    89,   144,   233,   377],
       [  610,   987,  1597,  2584,  4181],
       [ 6765, 10946, 17711, 28657, 46368]])

In [22]:
C=A+B#сложение двух матриц
C

array([[    1,     3,     4,     6,     8],
       [   11,    15,    21,    30,    44],
       [   66,   101,   157,   247,   392],
       [  626,  1004,  1615,  2603,  4201],
       [ 6786, 10968, 17734, 28681, 46393]])

In [27]:
D=np.array([[23, 21, 20, 13, 15],[ 18, 24, 21, 8, 5],[ 20, 3, 25, 6, 3], [1, 4, 11, 19, 12], [25, 15, 12, 12,24]])#заполняем матрицу случайными числами
D

array([[23, 21, 20, 13, 15],
       [18, 24, 21,  8,  5],
       [20,  3, 25,  6,  3],
       [ 1,  4, 11, 19, 12],
       [25, 15, 12, 12, 24]])

In [29]:
L=np.array([[1,-1/2,1/6,0,-1/30],[0,1/42,0,-1/30,0],
    [5/66,0,-691/2730,0,7/6],[0,-3617/510,0,43867/798,0],
    [-174611/330,0,854513,0,-236364091/2730]])#ряд бернулли
L

array([[ 1.00000000e+00, -5.00000000e-01,  1.66666667e-01,
         0.00000000e+00, -3.33333333e-02],
       [ 0.00000000e+00,  2.38095238e-02,  0.00000000e+00,
        -3.33333333e-02,  0.00000000e+00],
       [ 7.57575758e-02,  0.00000000e+00, -2.53113553e-01,
         0.00000000e+00,  1.16666667e+00],
       [ 0.00000000e+00, -7.09215686e+00,  0.00000000e+00,
         5.49711779e+01,  0.00000000e+00],
       [-5.29124242e+02,  0.00000000e+00,  8.54513000e+05,
         0.00000000e+00, -8.65802531e+04]])

In [30]:
W=L+D
W

array([[ 2.40000000e+01,  2.05000000e+01,  2.01666667e+01,
         1.30000000e+01,  1.49666667e+01],
       [ 1.80000000e+01,  2.40238095e+01,  2.10000000e+01,
         7.96666667e+00,  5.00000000e+00],
       [ 2.00757576e+01,  3.00000000e+00,  2.47468864e+01,
         6.00000000e+00,  4.16666667e+00],
       [ 1.00000000e+00, -3.09215686e+00,  1.10000000e+01,
         7.39711779e+01,  1.20000000e+01],
       [-5.04124242e+02,  1.50000000e+01,  8.54525000e+05,
         1.20000000e+01, -8.65562531e+04]])

In [ ]:
N=np.array([[10,72,80,62,34],
    [37,10,55,90,26],
    [45,41,15,14,44],
    [15,8,1,23,28],
    [67,39,89,4,23]])

In [38]:
E=C*W
E

array([[ 2.40000000e+01,  6.15000000e+01,  8.06666667e+01,
         7.80000000e+01,  1.19733333e+02],
       [ 1.98000000e+02,  3.60357143e+02,  4.41000000e+02,
         2.39000000e+02,  2.20000000e+02],
       [ 1.32500000e+03,  3.03000000e+02,  3.88526117e+03,
         1.48200000e+03,  1.63333333e+03],
       [ 6.26000000e+02, -3.10452549e+03,  1.77650000e+04,
         1.92546976e+05,  5.04120000e+04],
       [-3.42098711e+06,  1.64520000e+05,  1.51541464e+10,
         3.44172000e+05, -4.01560425e+09]])

In [ ]:
np.less(N,E)#полученная нами матрица меньше

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True,  True, False]])